FROM adoptopenjdk/openjdk14:alpine
RUN addgroup -S couponSys && adduser -S couponSys -G couponSys
USER couponSys:couponSys
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
